[package]
name = "aisha"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = { version = "5.0.0", default-features = false }

sled = { version = "0.34.7", features = ["compression"] }
